Updated the github action

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -48,6 +48,11 @@ jobs:
       - name: Install kubectl
         run: |
           KUBECTL_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
+          if [ -z "$KUBECTL_VERSION" ]; then
+            echo "Failed to fetch kubectl version"
+            exit 1
+          fi
+          echo "KUBECTL_VERSION: $KUBECTL_VERSION"
           curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
           chmod +x ./kubectl
           sudo mv ./kubectl /usr/local/bin/kubectl
@@ -57,9 +62,6 @@ jobs:
         run: |
           mkdir -p $HOME/.kube
           echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
-
-      - name: Display KUBECONFIG
-        run: cat $HOME/.kube/config
 
       - name: Test Kubernetes API Connectivity
         run: kubectl cluster-info
